version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "build"
    labels:
      - "area: build"
      - "merge ready"
      - "merge safe"
      - "target: patch"
    open-pull-requests-limit: 5
