version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    commit-message:
      prefix: "build"
    labels:
      - "area: build"
      - "merge ready"
      - "merge safe"
      - "target: patch"
