language: node_js
dist: trusty
sudo: false

node_js:
  # Use the explicit NodeJS LTS version 8.9.4 to avoid any automatic upgrade of the version.
  # This ensures that all Travis jobs run consistently and don't have different Node versions.
  - '8.12.0'

addons:
  jwt:
    # SAUCE_ACCESS_KEY<=secret for FIREBASE_ACCESS_TOKEN to work around travis-ci/travis-ci#7223, unencrypted value in valentine as FIREBASE_ACCESS_TOKEN>
    # we alias FIREBASE_ACCESS_TOKEN to $SAUCE_ACCESS_KEY in env.sh and set the SAUCE_ACCESS_KEY there
    - secure: "PKts/IbxuJRWWOEeiGbl8Z9zds0M+hIdCH/g/E4WbQ9yzSvSbdwzfmRfFccQFjxjsrY7+SJMVjsURZy+xUyBpzqgWYHUItnSVqjZb8DlyAU2IXyg8TM9BVLkGGe6k5k4PIFVmfMMMzQwWMM0X0W9w3oYmfHL5egxwSHvf9HIqLolLNXg8sqamIdS5d5KoCXf1c+oRjN/IMBktzNBR6N4OFOZQXVoepXNiIvTWAcTtOPBvFWdKP2n7RVioHKdm4a85aCUpDJp+LYGaLqiQZoRzmzfVTnAhTAPdd4ao5w/+jojrfZIHV55bqYF9rLnQMTneKsiyVNVYJzOLuxmARa/EEKfZld+J3rX4/o4cogrU38YSZF+T7J9g/7CTsnIZ3F6W6m+8iJbIBh55nGOQi5PVe458Q/nGb3fgQd2Z4+6lK9k479H4Ssh/Y7hbVQbepqEVIXzZKqWX6/ZE4iWoR/Q2dm0hySFmmB/R2etixX5JxhnHvgobTYIQ+1liJVp/3YFW1ru64Yg6yz/V291Bhh9g31znmTROCJ/usAmZZaLUqW1TDKnLIMP+M74MF9XERqcWKywXRFwxP4E5uDnx/vAyN49gL+SDfrBUxUtXrTkKZAlglwo9SgA7cOYEPWrionvKcGm87gCBYHFUmXZNQVzh212fpuJYXb/vy0sPDj8La4="
  chrome: stable
  firefox: latest

branches:
  only:
  - master
  # 5.2.x, 6.0.x, etc
  - /\d+\.\d+\.x/
  # 5.x, 6.x, etc
  - /\d+\.x/

jobs:
  include:
    - env: "MODE=payload"
    - env: "MODE=saucelabs_required"
    - env: "DEPLOY_MODE=dashboard"
      if: type = cron
env:
  global:
    # Keep Yarn version in sync with Yarn version within Bazel WORKSPACE.
    - YARN_VERSION=1.9.4
    - LOGS_DIR=/tmp/gngt-build/logs
    - SAUCE_USERNAME=angular-ci
    - BROWSER_STACK_USERNAME=gngt
    - BROWSER_STACK_ACCESS_KEY=CaXMeMHD9pr5PHg8N7Jq
    - BROWSER_PROVIDER_READY_FILE=/tmp/gngt-build/readyfile
    - BROWSER_PROVIDER_ERROR_FILE=/tmp/gngt-build/errorfile

before_install:
  - source ./scripts/ci/travis-env.sh
  - source ./scripts/ci/install-yarn.sh

install:
  - ./scripts/ci/travis-install.sh
  - if [[ "$TRAVIS_EVENT_TYPE" == "cron" ]]; then ./scripts/install-angular-snapshot.sh --only-save; fi

before_script:
  - mkdir -p $LOGS_DIR

script:
  - ./scripts/ci/travis-script.sh

cache:
  yarn: true
  directories:
    - ./node_modules/